name: Release

on:
  push:
    tags:
      - v*

env:
  DOCKER_BUILDX_VERSION: 'v0.8.2'
  UP_CLI_VERSION: 'v0.14.0'

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install up CLI
        env:
          VERSION: ${{ env.UP_CLI_VERSION }}
        run: |
          curl -sL https://cli.upbound.io | sh && mv up /usr/local/bin/ && up --version

      - name: Login to Upbound
        run: |
          up login --token ${{ secrets.XPKG_TOKEN }}

      - name: Build
        run: up xpkg build

      - name: Push
        run: up xpkg push ${{ github.repository }}:${{ github.ref_name }}
